### ISSUE TITLE
A life-saver for Bluetooth headphones

### ISSUE THREAD

**Issue by skygate2012** [anars/blank-audio#2]
![Bluetooth Headphones](https://user-images.githubusercontent.com/7148976/39161692-882d41ce-47a4-11e8-8be9-bd4c1be74aa1.jpg)
My Bluetooth headphones automatically stops receiving output from the computer when not playing anything for a certain amount of time in order to reduce the transmission noise as much as possible, which can be good for ears, but a great pain for discontinuing sounds such as synthesized sound effects. Now with these silent sound files I can play them on loop to conquer those stuttering caused by _receive-halt_. Silence is golden!

**Comment by rawr51919** [comment]
Agree, but this is completely unrelated to the repo itself. @anars, it should be OK to close this.
