### ISSUE TITLE
0ms of silence

### ISSUE THREAD

**Issue by jchook** [anars/blank-audio#9]
This is more of a question than a request: is it possible to have a 0ms mp3?

**Comment by jchook** [comment]
Found it! https://github.com/mathiasbynens/small

Thanks for this fantastic repo.

**Comment by mchun** [comment]
Just curious, what is your use case there to have a 0ms silence mp3?

**Comment by h3rcx** [comment]
Hi Alex, for meditation tracks that require different lengths


Hercules A. Juver
Branding | UX/UI | Dev enthusiast
+44 7760911920
Behance <https://www.behance.net/herculesjuver/>
[image: Linkedin] <https://www.linkedin.com/in/herculesjuver/>
<https://www.instagram.com/herculesjuver>

**Comment by mchun** [comment]
Thanks @h3rcx !
